### ISSUE TITLE
Integration with SenseCAP API (or SenseCAP Portal)

### ISSUE THREAD

**Issue by bigjdunham** [Seeed-Solution/home-assistant-SenseCAP#5]
Any chance you'd be able to get this integration to work with the SenseCAP API or the SenseCAP Portal? It would be quite helpful for those of us who have SenseCAP sensors but not gateways.

**Comment by QingWind6** [comment]
Hi, the SenseCraft version of Intergration should meet your requirements and you can download it from [here](https://github.com/Seeed-Solution/SenseCraft-HomeAssistant)

**Comment by QingWind6** [comment]
> Any chance you'd be able to get this integration to work with the SenseCAP API or the SenseCAP Portal? It would be quite helpful for those of us who have SenseCAP sensors but not gateways.

Hi, the SenseCraft version of Intergration should meet your requirements and you can download it from [here](https://github.com/Seeed-Solution/SenseCraft-HomeAssistant)
